version: "3"

services:

  product:
    image: e-commerce-product-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ecommerce-network

  recommendation:
    image: e-commerce-recommendation-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ecommerce-network

  review:
    image: e-commerce-review-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ecommerce-network

  product-composite:
    image: e-commerce-product-composite-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ecommerce-network

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongostat -n 1"
      interval: 5s
      timeout: 2s
      retries: 60
    networks:
      - ecommerce-network
    volumes:
      - ./dockerdata/db:/data/db

networks:
  ecommerce-network:

