spring.application.name: recommendation-service
server.port: 7002

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

logging:
  level:
    root: INFO
    com.ecommerce: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080

spring.data.mongodb:
  host: mongodb
  port: 27017
  database: recommendation-db